version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: loan_postgres
    restart: always
    environment:
       POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - infra_postgres_data:/var/lib/postgresql/data
  backend:
    build: 
     context: ../backend
     dockerfile: LoanService/Dockerfile
    container_name: loan_backend
    restart: always
    depends_on:
      - postgres
    environment:
      # строка подключения через переменные окружения
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=loan_db;Username=postgres;
    ports:
      - "5007:80"
volumes:
  infra_postgres_data:
