version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: loan_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loan_db
    ports:
      - "5432:5432"
    volumes:
      - infra_postgres_data:/var/lib/postgresql/data

  backend:
    image: gavr7k/loan_backend:latest
    container_name: loan_backend
    restart: always
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=loan_db;Username=postgres;Password=postgres
    ports:
      - "5007:80"

  frontend:
    image: gavr7k/loan_frontend:latest
    container_name: loan_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  infra_postgres_data:
